# @package _global_

# inherited from act.yaml
seed: 1000
dataset_repo_id: lerobot/pusht_keypoints


training:
  offline_steps: 100000
  online_steps: 0
  eval_freq: 20000
  save_freq: 20000
  save_checkpoint: true

  batch_size: 256
  lr: 1e-4
  lr_backbone: 1e-4
  grad_clip_norm: 10
  online_steps_between_rollouts: 1

  delta_timestamps:
    observation.environment_state: "[i / ${fps} for i in range(1 - ${policy.action_horizon}, 1)]"
    observation.state: "[i / ${fps} for i in range(1 - ${policy.action_horizon}, 1)]"
    action: "[i / ${fps} for i in range(1 - ${policy.action_horizon}, 1)]"

eval:
  n_episodes: 50
  batch_size: 5

# See `configuration_act.py` for more details.
policy:
  name: hpt
  domain_name: "pusht_keypoints"
  vision_backbone: "resnet18"
  pretrained_backbone_weights: "ResNet18_Weights.IMAGENET1K_V1"

  # Input / output structure.
  input_shapes:
    # TODO(rcadene, alexander-soare): add variables for height and width from the dataset/env?
    observation.environment_state: [16]
    observation.state: ["${env.state_dim}"]
  output_shapes:
    action: ["${env.action_dim}"]

  # Normalization / Unnormalization
  input_normalization_modes:
    observation.environment_state: min_max
    observation.state: min_max
  output_normalization_modes:
    action: min_max

  # HPT trunk config
  embed_dim: 256
  num_blocks: 16
  num_heads: 8
  use_modality_embedding: True
  use_domain_embedding: False
  token_postprocessing: "mean"
  weight_init_style: 'pytorch'
  drop_path: 0.0
  no_trunk: False
  load_pretrained: "" # load pre-trained model

  # stem network (projectors) for different modalities
  modalities: ['state']
  modality_embed_dim: "${policy.embed_dim}"
  normalize_state: True # normalize state vectors
  state_embedding_dim: 1
  image_encoder: resnet
  crossattn_dim_head: 64
  crossattn_heads: 8
  crossattn_modality_dropout: 0.1
  observation_horizon: 1
  random_horizon_masking: True # whether to randomize observation input length
  add_pos_embedding_to_state: False

  state_crossattn_latent: 16
  state_input_dim: 18 # ovewrite based on the dataset
  state_output_dim: "${policy.embed_dim}"
  state_widths: [128]
  state_num_of_copy: 1

  # head
  action_horizon: 4
  head_input_dim: "${policy.embed_dim}"
  head_tanh_end: True # normalized action output
  head_action_dim: "${env.action_dim}" # overwrite based on dataset
  head_dropout: True
  head_widths: [256, 128]
